doc:
  property:
  - fs: ''
  - listenAddr: ''
  - oauthScope: ''
  - oauthClientId: ''
  - oauthClientUrl: ''
  - os: ''
  - oauthTokenUrl: ''
  - oauthRedirectUrl: ''
  - oauthDefaultGroups: ''
  - oauthProvider: ''
  - listenPort: ''
  - redis: ''
  - spaceDefault: ''
  - oauthOrganization: ''
  - oauthClientUserInfoUrl: ''
  - oauthEnabled: ''
  - oauthSecret: ''
links:
  consume:
  - argname: fs
    auto: false
    max: 100
    min: '0'
    role: fs
  - argname: redis
    auto: false
    max: 100
    min: '0'
    role: redis
  parent:
    auto: false
    optional: false
    role: os
recurring: []
