doc:
  property:
  - host: ''
  - unixsocket: ''
  - appendonly: ''
  - os: ''
  - maxram: ''
  - fs: ''
  - port: ''
links:
  consume:
  - argname: fs
    auto: false
    max: 100
    min: '0'
    role: fs
  parent:
    auto: false
    optional: false
    role: os
recurring: []
