doc:
  property:
  - planType: ''
  - deviceId: ''
  - projectName: ''
  - deviceName: ''
  - deviceOs: ''
  - sshkey: ''
  - ipPublic: ''
  - ports: ''
  - sshLogin: ''
  - sshPassword: ''
  - location: ''
  - client: ''
links:
  consume:
  - argname: sshkey
    auto: true
    max: 100
    min: 0
    role: sshkey
  - argname: client
    auto: false
    max: '1'
    min: '1'
    role: packetnet_client
recurring: []
