doc:
  property:
  - docker: ''
  - fs: ''
  - sshPassword: ''
  - os: ''
  - cmd: ''
  - image: ''
  - sshkey: authorized sshkey
  - ipPublic: ''
  - ipPrivate: ''
  - ports: ''
  - sshLogin: ''
  - hostname: ''
  - volumes: ''
  - id: id of the container
links:
  consume:
  - argname: docker
    auto: false
    max: 100
    min: '0'
    role: app_docker
  - argname: fs
    auto: false
    max: 100
    min: '0'
    role: fs
  - argname: sshkey
    auto: true
    max: '1'
    min: '1'
    role: sshkey
  parent:
    auto: false
    optional: false
    role: os
recurring: []
