doc:
  property:
  - ipPublic: ''
  - sshAddr: ''
  - sshPassword: ''
  - ports: ''
  - sshLogin: ''
  - description: ''
  - sshPort: ''
  - sshkey: ''
links:
  consume:
  - argname: sshkey
    auto: true
    max: 100
    min: '1'
    role: sshkey
recurring: []
