doc:
  property:
  - oauthHost: ''
  - botToken: ''
  - fs: ''
  - oauthItsyouonlinehost: ''
  - oauthClient: ''
  - oauthPort: ''
  - os: ''
  - oauthSecret: ''
  - oauthRedirect: ''
links:
  consume:
  - argname: fs
    auto: false
    max: 100
    min: '0'
    role: fs
  parent:
    auto: false
    optional: false
    role: os
recurring: []
