doc:
  property:
  - accountID: ''
  - g8client: ''
  - accountusers: ''
  - maxMemoryCapacity: ''
  - maxCPUCapacity: ''
  - description: ''
  - maxNumPublicIP: ''
  - maxDiskCapacity: ''
links:
  consume:
  - argname: g8client
    auto: true
    max: 100
    min: 0
    role: g8client
  - argname: accountusers
    auto: true
    max: 100
    min: 0
    role: uservdc
recurring: []
