doc:
  property:
  - vmpool: ''
  - size: ''
  - backingStore: ''
links:
  consume:
  - argname: vmpool
    auto: false
    max: 100
    min: 0
    role: vmpool
  - argname: backingStore
    auto: false
    max: '1'
    min: '0'
    role: disk
recurring: []
