doc:
  property:
  - os: ''
  - vfsConfig: ''
links:
  consume:
  - argname: vfsConfig
    auto: false
    max: 100
    min: 0
    role: vfs_config
  parent:
    auto: false
    optional: false
    role: os
recurring: []
