doc:
  property:
  - sshAddr: ''
  - sshPort: ''
  - sshkey: ''
  - node: ''
links:
  consume:
  - argname: sshkey
    auto: true
    max: 100
    min: '1'
    role: sshkey
  parent:
    auto: false
    optional: false
    role: node
recurring: []
