doc:
  property:
  - hostprefix: ''
  - keySecret: ''
  - keyAccess: ''
  - sshkey: ''
  - enablehttps: ''
  - fqdn: ''
  - image: ''
  - disk: ''
  - vdc: ''
links:
  consume:
  - argname: sshkey
    auto: true
    max: 100
    min: '1'
    role: sshkey
  - argname: disk
    auto: false
    max: 100
    min: '0'
    role: disk
  parent:
    auto: true
    optional: false
    role: vdc
recurring: []
